version: "3.9"

services:
  db:
    image: postgres:14
    container_name: asset_pg
    environment:
      POSTGRES_USER: asset_user
      POSTGRES_PASSWORD: asset_pass
      POSTGRES_DB: asset_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: asset_api
    depends_on:
      - db
    ports:
      - "8123:8123"
    environment:
      DATABASE_URL: postgresql://asset_user:asset_pass@db:5432/engineering_asset_registry

volumes:
  pgdata:
